export { runDiagnostics } from "./diagnostics.ts"
export { compilePreset } from "./compile.ts"
export { createLayoutPlan } from "./planner.ts"
export { emitPlan } from "./emitter.ts"
export { compileFunctionalCorePipeline } from "./pipeline.ts"

export type { DiagnosticsReport, DiagnosticsSeverity } from "./diagnostics.ts"
export type { CompilePresetInput, CompilePresetSuccess, FunctionalPreset } from "./compile.ts"
export type { CreateLayoutPlanSuccess, LayoutPlan, PlanNode } from "./planner.ts"
export type { PlanEmission } from "./emitter.ts"
export type { FunctionalCoreError } from "./errors.ts"
export { isFunctionalCoreError } from "./errors.ts"
